# Generated by Django 2.1.2 on 2022-06-19 17:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='We provide food, shelter and protection. All are welcome.', null=True)),
                ('capacity', models.IntegerField(default=1000, null=True)),
                ('food', models.IntegerField(default=1000, null=True)),
                ('water', models.IntegerField(default=1000, null=True)),
                ('medicine', models.IntegerField(default=1000, null=True)),
                ('place_id', models.CharField(max_length=256, unique=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Relief Camps',
            },
        ),
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('description', models.TextField(default='Compromised area, keep distance', null=True)),
                ('weight', models.IntegerField(default=1)),
                ('disaster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Disaster')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=32, null=True)),
                ('emergencyName', models.CharField(max_length=32, null=True)),
                ('emergencyPhone', models.CharField(max_length=32, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('camp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Camp')),
            ],
        ),
        migrations.AddField(
            model_name='camp',
            name='disaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Disaster'),
        ),
    ]
